#!/bin/sh

encrypt()
{
    plaintext=$1
    hex_key=$(echo "$2" | openssl base64 -d | xxd -c32 -p)
    hex_iv=$(echo "$3" | openssl base64 -d | xxd -p)

    printf "$plaintext" |
        openssl aes-256-cbc -K "$hex_key" -iv "$hex_iv" -base64
}

encrypt "$@"
